### ISSUE TITLE
I see your secret! 

### ISSUE THREAD

**Issue by tristansokol** [lahorton/behavior_project#1]
https://github.com/lahorton/behavior_project/blob/d79158411078c5c01dc31b97ae9938c4c7f32f34/server.py#L18

I decent best practice is to use environment variables for secrets/passwords, etc. and then you don't have to worry about them being in the code: https://stackoverflow.com/questions/14786072/keep-secret-keys-out

**Comment by lahorton** [comment]
Yep!  I know...I need to fix that so it's in a secrets file.  I was being lazy.  Thank you!

**Comment by lahorton** [comment]
Fixed :)
