### ISSUE TITLE
This project could us a Readme! 

### ISSUE THREAD

**Issue by tristansokol** [lahorton/behavior_project#2]
It might seem like the best time to document everything is at the end, but keeping a lightweight readme up to date while you go can be really useful, (especially as people might start checking out the project) 

I'd probably just start with adding a new `readme.md` file and putting a title and a short paragraph about what is going on. 

It can also be a good place to store all of the commands you need to get things up and running. Writing down a database import script can be pretty useful if you don't use it often and then are trying to look back in your bash history to find out what you were doing. :)

**Comment by lahorton** [comment]
Got it!  

Summary is up for now.  I'll try to add requirements/install this week :)  Thanks for the reminder :)
